In [1]:
import numpy as np
import torch
import warnings
warnings.filterwarnings("ignore")

#### randn :

In [2]:
#using rand = a tensor filled with random numbers from a uniform distribution on the interval [0,1)
print(torch.rand(2, 4), '\n')
print(torch.rand(3, 4, 4), '\n')
print(torch.rand(2, 3, 4, 2), '\n')
print(torch.rand(2, 2).ndim, '\n')
print(torch.rand(3, 4, 4).ndim, '\n')
print(torch.rand(2, 3, 4, 2).ndim, '\n')
print(type(torch.rand(2, 4)))

tensor([[0.9603, 0.7293, 0.7175, 0.7876],
        [0.4966, 0.1068, 0.3441, 0.2281]]) 

tensor([[[0.2917, 0.2003, 0.1385, 0.6404],
         [0.4497, 0.0209, 0.7296, 0.5024],
         [0.3015, 0.3328, 0.2406, 0.3160],
         [0.2955, 0.8884, 0.1081, 0.9027]],

        [[0.6526, 0.8514, 0.1534, 0.9087],
         [0.3857, 0.7685, 0.1217, 0.9739],
         [0.1558, 0.1783, 0.5755, 0.3042],
         [0.7331, 0.5197, 0.7407, 0.4475]],

        [[0.0120, 0.7631, 0.2962, 0.0618],
         [0.2830, 0.4649, 0.2571, 0.1484],
         [0.3234, 0.9269, 0.3266, 0.1855],
         [0.5627, 0.9580, 0.8475, 0.2891]]]) 

tensor([[[[0.1799, 0.0228],
          [0.4573, 0.8966],
          [0.6424, 0.1906],
          [0.7137, 0.5785]],

         [[0.0602, 0.3249],
          [0.2669, 0.6232],
          [0.3630, 0.4187],
          [0.2531, 0.1513]],

         [[0.7481, 0.3973],
          [0.8598, 0.4958],
          [0.5867, 0.8183],
          [0.7864, 0.2090]]],


        [[[0.4675, 0.2429],
          [0.1646

#### randn :

In [3]:
#using randn = a tensor filled with random numbers from a normal distribution with mean 0 and variance 1 (also called the standard normal distribution).
print(torch.randn(2, 4), '\n')
print(torch.randn(3, 4, 4), '\n')
print(torch.randn(2, 3, 4, 2), '\n')
print(torch.randn(2, 2).ndim, '\n')
print(torch.randn(3, 4, 4).ndim, '\n')
print(torch.randn(2, 3, 4, 2).ndim, '\n')
print(type(torch.randn(2, 4)))
print(torch.randn(2,2, dtype=torch.float32))

tensor([[ 1.3905,  0.3913, -0.5759, -0.8838],
        [-0.0876, -0.9079,  1.6618, -1.0972]]) 

tensor([[[ 1.1695, -1.2646,  0.9997,  0.1969],
         [ 0.1920,  1.0070,  1.5556,  0.3725],
         [ 0.2223,  0.1780, -0.5405, -0.5482],
         [ 0.9280, -0.4204, -0.4194, -1.5897]],

        [[-2.2447, -0.2657,  0.1960,  0.6324],
         [-0.2677,  0.0535,  1.6735,  0.1190],
         [ 0.0138,  0.4975, -0.9782,  1.7645],
         [-0.9788, -0.5776,  1.4876, -0.4119]],

        [[-0.5925, -1.7759, -0.0908, -0.4957],
         [-0.5309, -0.4317, -0.6975, -1.6743],
         [-0.6322,  0.5757, -0.1164,  1.0384],
         [ 1.1088, -2.7816, -1.9721,  1.0592]]]) 

tensor([[[[-0.5785, -0.8998],
          [ 0.4896, -1.9025],
          [ 0.4977,  0.2620],
          [-0.4636,  0.8803]],

         [[-0.3128,  1.0509],
          [ 0.7030, -0.7921],
          [-0.5532,  0.2298],
          [ 1.3068,  0.3100]],

         [[ 0.7849,  0.9119],
          [ 1.1339, -1.3573],
          [-0.0907, -0.2792],

#### randint :

In [4]:
print(torch.randint(0, 10, (3, 4)), '\n')
print(torch.randint(low = 1, high = 10, size = (3, 4, 3)), '\n')
print(torch.randint(low = 1, high = 10, size = (3, 4, 3)).ndim, '\n')

tensor([[7, 6, 8, 7],
        [7, 8, 1, 8],
        [0, 0, 0, 4]]) 

tensor([[[6, 1, 6],
         [5, 4, 6],
         [5, 6, 1],
         [5, 6, 1]],

        [[9, 5, 4],
         [2, 9, 1],
         [2, 6, 3],
         [7, 4, 9]],

        [[9, 1, 2],
         [2, 2, 5],
         [1, 4, 8],
         [4, 7, 3]]]) 

3 



#### datatype :

In [5]:
a = torch.tensor([0.123456789, 2, 3], dtype= torch.float16)
print('16bit  :' , a[0])

b = torch.tensor([0.123456789, 2, 3], dtype= torch.float32)
print('32bit  :' , b[0])

c = torch.tensor([0.123456789, 2, 3], dtype= torch.float64)
print('64bit  :' , c[0])

print('Memory usage of 16-bit float tensor:', a.element_size() * a.nelement())
print('Memory usage of 32-bit float tensor:', b.element_size() * b.nelement())
print('Memory usage of 64-bit float tensor:', c.element_size() * c.nelement())
#the precision will be higher as the float types increased but computation will be slow

16bit  : tensor(0.1235, dtype=torch.float16)
32bit  : tensor(0.1235)
64bit  : tensor(0.1235, dtype=torch.float64)
Memory usage of 16-bit float tensor: 6
Memory usage of 32-bit float tensor: 12
Memory usage of 64-bit float tensor: 24


In [6]:
#create all zeros and ones

print(torch.zeros(3, 3), '\n')
print(torch.zeros(3, 3, dtype=torch.int), '\n') #change datatype

print(torch.ones(3, 3), '\n')
print(torch.ones(3, 3, dtype=torch.int), '\n')

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) 

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32) 

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32) 



#### concat :

In [7]:
#Concat #axis
print(torch.randint(1, 5, (2,4)))
print(torch.randint(1, 5, (4,4)))

print("cancatination on column-wise :", '\n')
tensor1 = torch.randint(1, 4, (2, 2))
tensor2 = torch.randint(4, 6, (2, 4))
concatenated_tensor = torch.concat((tensor1, tensor2), axis=1)
print(tensor1, '\n')
print(tensor2, '\n')
print(concatenated_tensor, '\n')
print(concatenated_tensor.shape, '\n')

#cat #dim
print("cancatination on row-wise :", '\n')
tensor11 = torch.randint(1, 4, (3, 4))
tensor12 = torch.randint(4, 6, (2, 4))
concatenated_tensor2 = torch.cat((tensor11, tensor12), dim=0)
print(tensor11, '\n')
print(tensor12, '\n')
print(concatenated_tensor2, '\n')
print(concatenated_tensor2.shape, '\n')

#can be used dim instead of a

tensor([[1, 1, 1, 1],
        [2, 1, 3, 3]])
tensor([[1, 4, 3, 4],
        [1, 1, 2, 4],
        [3, 1, 2, 2],
        [2, 2, 2, 4]])
cancatination on column-wise : 

tensor([[2, 3],
        [2, 2]]) 

tensor([[5, 4, 4, 4],
        [5, 4, 5, 4]]) 

tensor([[2, 3, 5, 4, 4, 4],
        [2, 2, 5, 4, 5, 4]]) 

torch.Size([2, 6]) 

cancatination on row-wise : 

tensor([[1, 2, 2, 1],
        [1, 1, 2, 1],
        [3, 2, 1, 1]]) 

tensor([[5, 4, 4, 4],
        [4, 4, 5, 5]]) 

tensor([[1, 2, 2, 1],
        [1, 1, 2, 1],
        [3, 2, 1, 1],
        [5, 4, 4, 4],
        [4, 4, 5, 5]]) 

torch.Size([5, 4]) 



In [8]:
print("pointwise addition :", '\n')
tensor1 = torch.randint(1, 4, (2, 4))
tensor2 = torch.randint(4, 6, (2, 4))
concatenated_tensor = torch.tensor((tensor1+tensor2))
print(tensor1, '\n')
print(tensor2, '\n')
print(concatenated_tensor, '\n')
print(concatenated_tensor.shape, '\n')

pointwise addition : 

tensor([[3, 2, 2, 3],
        [1, 3, 1, 1]]) 

tensor([[4, 5, 4, 5],
        [4, 4, 4, 5]]) 

tensor([[7, 7, 6, 8],
        [5, 7, 5, 6]]) 

torch.Size([2, 4]) 



In [9]:
#reshaping
a = torch.rand(4, 3, dtype=torch.float16)
print(a, '\n')

#changing the shape from 4 rows 2 & 3 respectively where -1 helps us to determine the column automatically
print(a.reshape(2, -1), '\n')
print(a.view(3, -1))
#can use reshape and view

tensor([[0.8750, 0.3838, 0.1343],
        [0.6216, 0.7573, 0.3745],
        [0.7422, 0.7285, 0.7798],
        [0.7998, 0.7109, 0.3657]], dtype=torch.float16) 

tensor([[0.8750, 0.3838, 0.1343, 0.6216, 0.7573, 0.3745],
        [0.7422, 0.7285, 0.7798, 0.7998, 0.7109, 0.3657]], dtype=torch.float16) 

tensor([[0.8750, 0.3838, 0.1343, 0.6216],
        [0.7573, 0.3745, 0.7422, 0.7285],
        [0.7798, 0.7998, 0.7109, 0.3657]], dtype=torch.float16)


In [10]:
#dimension expand

x= torch.randint(1, 9, (3, 4))
print(x, '\n')
print('dimension of x is :', x.ndim, '\n')
print('shape of x is :', x.shape, '\n')

y=torch.unsqueeze(x, dim=1)
print(y, '\n')
print('shape of y is :', y.shape, '\n')

z=torch.unsqueeze(x, dim=0)
print(z, '\n')
print('shape of z is :', z.shape, '\n')

tensor([[6, 8, 2, 2],
        [6, 6, 1, 8],
        [1, 8, 8, 2]]) 

dimension of x is : 2 

shape of x is : torch.Size([3, 4]) 

tensor([[[6, 8, 2, 2]],

        [[6, 6, 1, 8]],

        [[1, 8, 8, 2]]]) 

shape of y is : torch.Size([3, 1, 4]) 

tensor([[[6, 8, 2, 2],
         [6, 6, 1, 8],
         [1, 8, 8, 2]]]) 

shape of z is : torch.Size([1, 3, 4]) 



In [11]:
#value findings

x= torch.randint(1, 9, (3, 4))
print(x, '\n')
limit = 3
print(torch.where(x > limit, True, False), '\n')
print(x[torch.where(x > limit, True, False)])

tensor([[5, 6, 6, 3],
        [2, 8, 7, 1],
        [2, 8, 5, 2]]) 

tensor([[ True,  True,  True, False],
        [False,  True,  True, False],
        [False,  True,  True, False]]) 

tensor([5, 6, 6, 8, 7, 8, 5])


In [12]:
###SPLIT

#hsplit works column-wise
torch.manual_seed(11)
x= torch.rand(1, 6)
print(x, '\n')

print(torch.hsplit(x, 3), '\n')
print(torch.hsplit(x, 2), '\n')
print(torch.hsplit(x, 6), '\n')

#vsplit works row-wise
y= torch.rand(3, 3)
print(y, '\n')
print(torch.vsplit(y, 3), '\n')

tensor([[0.1490, 0.4866, 0.9857, 0.1684, 0.5839, 0.6936]]) 

(tensor([[0.1490, 0.4866]]), tensor([[0.9857, 0.1684]]), tensor([[0.5839, 0.6936]])) 

(tensor([[0.1490, 0.4866, 0.9857]]), tensor([[0.1684, 0.5839, 0.6936]])) 

(tensor([[0.1490]]), tensor([[0.4866]]), tensor([[0.9857]]), tensor([[0.1684]]), tensor([[0.5839]]), tensor([[0.6936]])) 

tensor([[0.5831, 0.1284, 0.5721],
        [0.9248, 0.2693, 0.7825],
        [0.2719, 0.4632, 0.7671]]) 

(tensor([[0.5831, 0.1284, 0.5721]]), tensor([[0.9248, 0.2693, 0.7825]]), tensor([[0.2719, 0.4632, 0.7671]])) 



In [13]:
#Transposing : row to column and vice-versa

y= torch.randint(1, 4, (1,3))
print(y, '\n')
print(y.T, '\n')

tensor([[1, 3, 1]]) 

tensor([[1],
        [3],
        [1]]) 



In [14]:
#Sortung

y= torch.randint(1, 4, (1,3)).sort(descending = False)
print(y, '\n')

x= torch.randint(1, 4, (2,3)).sort(descending = True)
print(x, '\n')

torch.return_types.sort(
values=tensor([[1, 2, 2]]),
indices=tensor([[2, 0, 1]])) 

torch.return_types.sort(
values=tensor([[3, 2, 2],
        [2, 2, 1]]),
indices=tensor([[1, 0, 2],
        [1, 2, 0]])) 



In [15]:
#ADDITION
x = torch.randn(3, 2)
y = torch.randn(3, 2)
print(x + y, '\n\n')
#can use this one also for elementwise addition
print(torch.add(x, y), '\n')

#SUBTRACTION
print(x-y, '\n\n')
print(torch.sub(x, y), '\n')

#MULTIFICATION
print(x*y, '\n\n')
print(torch.mul(x, y), '\n')

#divition
print(x/y, '\n\n')
print(torch.div(x, y))

tensor([[-2.0150, -0.1333],
        [-1.6338,  1.1260],
        [-0.5514, -1.8728]]) 


tensor([[-2.0150, -0.1333],
        [-1.6338,  1.1260],
        [-0.5514, -1.8728]]) 

tensor([[ 1.4572, -0.0087],
        [ 0.6494,  1.8418],
        [-1.4104,  0.2495]]) 


tensor([[ 1.4572, -0.0087],
        [ 0.6494,  1.8418],
        [-1.4104,  0.2495]]) 

tensor([[ 0.4842,  0.0044],
        [ 0.5619, -0.5311],
        [-0.4213,  0.8613]]) 


tensor([[ 0.4842,  0.0044],
        [ 0.5619, -0.5311],
        [-0.4213,  0.8613]]) 

tensor([[ 0.1607,  1.1396],
        [ 0.4312, -4.1461],
        [-2.2839,  0.7649]]) 


tensor([[ 0.1607,  1.1396],
        [ 0.4312, -4.1461],
        [-2.2839,  0.7649]])


In [16]:
#Mean,SQRT >>>>

x = torch.rand(2, 3)
y = torch.rand(2, 3)
print(x, '\n')
print(y, '\n')
print(torch.mean(x), '\n\n')
print(torch.median(x), '\n\n')
print(torch.std(x), '\n\n')
print(torch.sqrt(x), '\n\n')
print(torch.mode(x), '\n\n')

tensor([[0.7171, 0.4578, 0.3566],
        [0.4831, 0.6752, 0.2525]]) 

tensor([[0.5272, 0.8281, 0.4956],
        [0.8292, 0.0482, 0.0826]]) 

tensor(0.4904) 


tensor(0.4578) 


tensor(0.1795) 


tensor([[0.8468, 0.6766, 0.5972],
        [0.6951, 0.8217, 0.5025]]) 


torch.return_types.mode(
values=tensor([0.3566, 0.2525]),
indices=tensor([2, 2])) 




In [17]:
#Convertion

x = torch.rand(3, 2)
print(x, '\n')

y = x.numpy()
z = np.random.rand(3, 2)

print(z, '\n')
print(torch.from_numpy(z))

tensor([[0.2730, 0.7694],
        [0.8017, 0.1284],
        [0.6878, 0.4103]]) 

[[0.04713878 0.60683687]
 [0.61603407 0.63882602]
 [0.19001695 0.16388603]] 

tensor([[0.0471, 0.6068],
        [0.6160, 0.6388],
        [0.1900, 0.1639]], dtype=torch.float64)
